openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
  description: Library
servers:
  - url: http://localhost:8080
    description: Server
paths:
  /webapp/JSP/Entrance.jsp:
    post:
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 1
              required:
                - login
                - password
            example:
              login: vova
              password: pass
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  login:
                    type: string
                  password:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: Invalid login or password
      summary: Login
      description: Logs in a user with a login and password.