openapi: 3.0.3
info:
  description: Library
  title: Library
  version: 1.0.0
servers:
- description: Server
  url: http://localhost:8080
paths:
  /webapp/JSP/Entrance.jsp:
    post:
      description: Logs in a user with a login and password.
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            example:
              login: vova
              password: pass
            schema:
              properties:
                login:
                  minLength: 1
                  type: string
                password:
                  minLength: 1
                  type: string
              required:
              - login
              - password
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
        "400":
          content:
            application/json:
              example:
                error: Invalid login or password
              schema:
                $ref: '#/components/schemas/inline_response_400'
          description: Bad Request
      summary: Login
      tags:
      - login
      x-contentType: application/json
      x-accepts: application/json
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
  schemas:
    inline_object:
      properties:
        login:
          minLength: 1
          type: string
        password:
          minLength: 1
          type: string
      required:
      - login
      - password
      type: object
    inline_response_200:
      example:
        password: password
        id: 0
        login: login
      properties:
        id:
          type: integer
        login:
          type: string
        password:
          type: string
      type: object
    inline_response_400:
      properties:
        error:
          type: string
      type: object

